name: Deploy to AWS

on:
    workflow_dispatch:
        inputs:
            processing_image_tag:
                description: "Processing image tag"
                required: true
            deploy_environment:
                description: "Deployment environment (e.g., staging, production)"
                required: true

env:
    TF_VAR_processing_image_tag: ${{ github.event.inputs.processing_image_tag }}
    TF_VAR_app_environment: ${{ github.event.inputs.deploy_environment }}
    TF_VAR_NODE_ENV: ${{ github.event.inputs.deploy_environment }}

jobs:
    check-admin:
      runs-on: ubuntu-latest
      steps:
        - uses: ./.github/workflows/check-admin.yml
          with:
              github_token:  ${{ secrets.GITHUB_TOKEN }}

    validate-environment:
        name: Validate environment
        runs-on: ubuntu-latest
        steps:
            - uses: ./.github/workflows/validate-environment.yml
              with:
                  deploy_environment: ${{ github.event.inputs.deploy_environment }}

    deploy:
        name: Terraform Deployment
        runs-on: ubuntu-latest
        environment:
            name: ${{ github.event.inputs.deploy_environment }}
        steps:
            - name: Load environment variables
              run: |
                  echo "$ENV_FILE" > myenvfile
                  source myenvfile
                  env
              env:
                ENV_FILE: ${{ env.ENV_FILE }} 

            - name: Checkout Repository
              uses: actions/checkout@v3

            - name: Setup Terraform
              uses: hashicorp/setup-terraform@v1
              with:
                  terraform_version: "1.4.6"

            - name: Set up AWS CLI
              uses: aws-actions/configure-aws-credentials@v1
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-region: us-east-2

            - name: Terraform Init
              working-directory: deployment/environments/${{ github.event.inputs.deploy_environment }}
              run: terraform init

            - name: Terraform Plan
              working-directory: deployment/environments/${{ github.event.inputs.deploy_environment }}
              run: terraform plan

            - name: Terraform Apply with Auto Confirm
              working-directory: deployment/environments/${{ github.event.inputs.deploy_environment }}
              run: terraform apply -auto-approve
