name: Main Workflow

on:
    pull_request:
        types: [opened, synchronize]
        branches:
            - dev
            - main

concurrency:
    group: ${{github.workflow}}-${{github.ref}}
    cancel-in-progress: true

jobs:
    build:
        uses: ./.github/workflows/base/build.yml

    build-image:
        uses: ./.github/workflows/base/build-image.yml

    lint:
        uses: ./.github/workflows/base/lint.yml
        needs: build

    test:
        uses: ./.github/workflows/base/test.yml
        needs: lint

    test-integration:
        uses: ./.github/workflows/base/test-integration.yml
        needs: lint
